### ISSUE TITLE
Bot only replacing text, not link

### ISSUE THREAD

**Issue by Ruakij** [GitGangGuy/reddit-privacy-pal#1]
I have noticed, the following post from the bot:
https://www.reddit.com/r/selfhosted/comments/nql52n/budibase_09_release_build_and_selfhost_internal/h0b3up3?utm_source=share&utm_medium=web2x&context=3

As you can see, the youtube-link-text was replaced, but the html-link was not.

I have not checked for more of these errors, just adding this as iusse to look into it.

**Comment by GitGangGuy** [comment]
Ah now I see! Apparently the [url regex I'm using](https://github.com/niftylettuce/url-regex-safe) matches closing and opening parentheses/brackets, so a markdown link like `[https://youtu.be/zI8TgTNNg04](https://youtu.be/zI8TgTNNg04)` will be picked up as a single URL (excluding the opening square bracket), not two. I have worked around this by replacing all occurrences of YouTube strings within a URL, not just the first per match. Should be fixed in a few minutes.
